# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a14cecd61bdcfd977cf522044927eccd91ca5b1b858a4282fcce211db9345689e557015c89d6e8660292924b0ecbfa21c3eda9049684110e0ca5e700cd92a05

test:
  secret_key_base: e43d6f76b4aaf997df89577a569692f09d52c6e8ec443cd669a01d0a68afde5b32a436c53be0ec5da90920bc957de4550449987f0f7bd6f943df24e40a5e17da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
